### ISSUE TITLE
Suggestion: New loglevel SUCCESS

### ISSUE THREAD

**Issue by wedi** [xolox/python-verboselogs#4]
Hi Peter!
For a project of mine I am going to add an additional log level `SUCCESS` to have it differently styled with `coloredlogs`. Would you be interested in a pull request? If yes, we can discuss where it should sit. Personally I’d add it between `WARNING` and `ERROR`. This way one can avoid all output when something succeeds and still have a success message when very limited information is desired only.
dirk

**Comment by xolox** [comment]
Hi Dirk and thanks for the suggestion.

While it had never occurred to me to define the SUCCESS log level I think I understand it's usefulness, both from your description and from xolox/python-coloredlogs/issues/27. However I'm not yet sure about the "position" you're suggesting:

- 10 - DEBUG
- 15 - VERBOSE
- 20 - INFO
- 25 - NOTICE
- 30 - WARNING
- **35 - SUCCESS** (somewhere between WARNING and ERROR, the exact integer value is not important)
- 40 - ERROR
- 50 - CRITICAL

Before reading the text of this issue and the other one I had assumed that the suggestion would be to put the new SUCCESS log level between INFO and WARNING, something like this:

- 10 - DEBUG
- 15 - VERBOSE
- 20 - INFO
- **22 - SUCCESS**
- 25 - NOTICE
- 30 - WARNING
- 40 - ERROR
- 50 - CRITICAL

Taking a step back, I think we agree that SUCCESS comes "after" INFO. So I guess the question is what comes "after" SUCCESS? :slightly_smiling_face:

**Comment by wedi** [comment]
Hi Peter,
I see reasons for both positions. While the latter is definitely more intuitive looking at the severity, the former is better when looking at scripts that use logging as a means of user output instead of (or in addition to) - more technical - logging. Adding success between 30 and 40 allows to reduce the output to failure and success, adding more information on request only.

One compromise would be to add OK (22) and SUCCESS (35), another one to add SUCCESS as 28.

**Comment by xolox** [comment]
After some more thinking I've decided to go ahead with the log level you originally implied (35) and published verboselogs 1.7 which adds support for the [SUCCESS](http://verboselogs.readthedocs.io/en/latest/api.html#verboselogs.SUCCESS) log level. I'm not really happy with the description in the table in the readme so if you have suggestions then I'm all ears :slightly_smiling_face:.
