### ISSUE TITLE
Cyclic test dependencies between coloredlogs and verboselogs 

### ISSUE THREAD

**Issue by ghisvail** [xolox/python-verboselogs#8]
I am wondering whether `verboselogs` could be tested without `coloredlogs`? Since both depend on each other for tests, there is no way I can bootstrap Debian packages (with tests running) for both. Considering how simple `verboselogs` is, perhaps it would be possible to just depend on a standard logger for his test suite?

**Comment by xolox** [comment]
Thanks for the feedback, this is now fixed and released as 1.6.2.
